#!/bin/sh

echo "Running checks before push..."

echo "Checking migrations"
python manage.py makemigrations --check
if [ $? -ne 0 ]; then
    echo "Migrations need to be made. Push aborted."
    exit 1
fi

echo "Running tests"
python manage.py test
if [ $? -ne 0 ]; then
    echo "Tests failed. Push aborted."
    exit 1
fi

echo "Checks passed. Pushing..."
exit 0