# Generated by Django 6.1 on 2026-08-30 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verse',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='selections.book'),
        ),
        migrations.AddField(
            model_name='hiddenrange',
            name='end_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_hidden_ranges', to='selections.verse'),
        ),
        migrations.AddField(
            model_name='hiddenrange',
            name='start_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_hidden_ranges', to='selections.verse'),
        ),
        migrations.AddField(
            model_name='verserange',
            name='end_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_verse_ranges', to='selections.verse'),
        ),
        migrations.AddField(
            model_name='verserange',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_ranges', to='selections.selection'),
        ),
        migrations.AddField(
            model_name='verserange',
            name='start_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_verse_ranges', to='selections.verse'),
        ),
        migrations.AddField(
            model_name='hiddenrange',
            name='verse_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_ranges', to='selections.verserange'),
        ),
    ]
