# Generated by Django 6.1 on 2026-08-31 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selections.verse')),
            ],
        ),
        migrations.CreateModel(
            name='AudioSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_template', models.CharField()),
                ('name', models.CharField(default='')),
                ('base_offset', models.IntegerField(default=0)),
                ('version', models.CharField(default='King James Version')),
                ('version_abbr', models.CharField(default='KJV')),
            ],
        ),
        migrations.CreateModel(
            name='AudioOffsetSuggestion',
            fields=[
                ('audiooffset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='selections.audiooffset')),
            ],
            bases=('selections.audiooffset',),
        ),
        migrations.CreateModel(
            name='AudioSourceSuggestion',
            fields=[
                ('audiosource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='selections.audiosource')),
            ],
            bases=('selections.audiosource',),
        ),
        migrations.AddField(
            model_name='audiooffset',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selections.audiosource'),
        ),
        migrations.AddField(
            model_name='selection',
            name='audio_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='selections.audiosource'),
        ),
    ]
