# Generated by Django 6.1 on 2026-08-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0003_audiooffset_audiosource_audiooffsetsuggestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='voice',
            new_name='browser_voice',
        ),
    ]
