# Generated by Django 6.1 on 2026-08-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0004_rename_voice_selection_browser_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiosource',
            old_name='base_offset',
            new_name='default_offset',
        ),
        migrations.AddField(
            model_name='verserange',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiooffset',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_offsets', to='selections.audiosource'),
        ),
        migrations.AlterField(
            model_name='audiooffset',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_offsets', to='selections.verse'),
        ),
    ]
