# Generated by Django 6.1 on 2026-08-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0005_rename_base_offset_audiosource_default_offset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosource',
            name='name',
            field=models.CharField(),
        ),
    ]
