# Generated by Django 6.0.1 on 2026-02-26 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(unique=True)),
                ('voice', models.CharField()),
                ('repeat', models.IntegerField()),
                ('version', models.CharField()),
                ('read_label', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=0)),
                ('verse', models.IntegerField(default=0)),
                ('kjv', models.CharField(verbose_name='King James Version')),
                ('gnb', models.CharField(default='', verbose_name='Good News Bible')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='selection.book')),
            ],
        ),
        migrations.CreateModel(
            name='VerseRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_range', to='selection.verse')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.selection')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_range', to='selection.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Hidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_hidden', to='selection.verse')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_hidden', to='selection.verse')),
                ('hidden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.verserange')),
            ],
        ),
    ]
