# Generated by Django 6.0.1 on 2026-02-17 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('kjv', models.CharField(verbose_name='King James Version')),
                ('gnb', models.CharField(default='', verbose_name='Good News Bible')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(unique=True)),
                ('voice', models.CharField()),
                ('repeat', models.IntegerField()),
                ('version', models.CharField()),
                ('read_label', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.selection')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_range', to='selection.verse')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_range', to='selection.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Hidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.range')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_hidden', to='selection.verse')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_hidden', to='selection.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_chapter', to='selection.verse')),
                ('start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_chapter', to='selection.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('end_chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_book', to='selection.chapter')),
                ('start_chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_book', to='selection.chapter')),
                ('end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_book', to='selection.verse')),
                ('start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_book', to='selection.verse')),
            ],
        ),
    ]
