# Generated by Django 6.0.1 on 2026-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='voice',
            field=models.CharField(default='default'),
        ),
    ]
