# Generated by Django 6.0.1 on 2026-02-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Range',
            new_name='VerseRange',
        ),
    ]
